import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import UserLayout from "./_component/Userlayout";
import "./_styles/user-module.css";
import { ROUTES } from "@/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sesion = await auth();
  if (!sesion) {
    redirect(ROUTES.LOGIN);
  }
  return (
    <div className="user-route-container">
      <UserLayout>{children}</UserLayout>
    </div>
  );
}
