import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title> Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <main className={styles.main}>
          <div className={styles.title_Main}>
            <h1 className={styles.title}>Hunter Coder</h1>
            <p className={styles.description}>
              A blog for hunting coders by a hunting coder
            </p>
          </div>
          <div className={styles.blogs}>
            <Image
              src="/coderImg.webp"
              height={200}
              width={500}
              alt="coderImg "
            />
            <h2 className={styles.populer_Blog}> Populer Blogs</h2>
            <div className={styles.blogItem}>
              <Link href="/blogpost/0">
                <h3>How to learn javascript in 2022?</h3>
              </Link>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <Link href="/blogpost/1">
                <h3>How to learn javascript in 2022?</h3>
              </Link>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <Link href="/blogpost/2">
                <h3>How to learn javascript in 2022?</h3>
              </Link>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
          </div>
        </main>
      </>
    </>
  );
}
