import Head from "next/head";
import styles from "@/styles/Home.module.css";
import LayOut from "@/component/Layout";
import { useQuery } from "@apollo/client";
import { TOP_MOVIE_LISTS } from "@/graphql/query";
import { Breadcrumb, Col, Row, Spin } from "antd";
import MovieCard from "@/component/MovieCard";
import TitleBar from "@/component/TitleBar";

export default function Home() {
  const { data, loading } = useQuery(TOP_MOVIE_LISTS, {
    variables: {
      filter: {
        category: "TOP_RATED",
        limit: 5,
      },
      sort: {
        field: "createdAt",
      },
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayOut
        breadCrumb={
          <Breadcrumb
            style={{
              margin: "16px 0",
            }}
          >
            <Breadcrumb.Item> / Home</Breadcrumb.Item>
          </Breadcrumb>
        }
      >
        <TitleBar
          title={`TOP 5 MOVIES`}
          icon=""
          link=""
          TooLtip=""
          display="none"
          input="none"
        />
        <div className={styles.movieListContainer}>
          {!loading ? (
            <Row>
              {data &&
                data.listMovies.data.map((movie) => {
                  const { budget, id, title } = movie;
                  return (
                    <Col
                      key={movie.id}
                      xs={{
                        span: 4,
                      }}
                      lg={{
                        span: 6,
                      }}
                    >
                      <MovieCard
                        budget={budget}
                        id={id}
                        title={title}
                        cover={
                          <img
                            style={{ width: "100%" }}
                            alt="example"
                            src="https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png"
                          />
                        }
                        textAlign="start"
                        pushLink="/"
                        AddFavioritIconHide="none"
                      />
                    </Col>
                  );
                })}
            </Row>
          ) : (
            <Spin className={styles.spiner} size="large" />
          )}
        </div>
      </LayOut>
    </>
  );
}
