export const CONSTATNTS = {
  TMDB: "TMDB",
  TOP_5_MOVIES: "Top 5 Movies",
  BACK_TO_HOME: "Back Home",
  LOGIN: "Login",
  REGISTER_NOW: "Register now!",
  OR: "Or",
  TITLE: "Title",
  BUDGET: "Budget",
  REVENUE: "Revenue",
  NAME: "Name",
  DEPARTMENT: "Department",
  GENDER: "Gender",
  SINGUP: "Singup",
  LOGIN_NOW: "Login now!",
  ADD_MOVIE: "Add Movie",
  TRUE: "TRUE",
  FALSE: "FALSE",
  NO_DATA: "No Data",
  PLEASE_INPUT_YOUR_MOVIE: "Please input your movie",
  ORIGINALTITLE: "OriginalTitle",
  ORIGINALLANGUAGE: "OriginalLanguage",
  OVERVIEW: "Overview",
  STATUS: "Status",
  TAGLINE: "Tagline",
  RELEASEDATE: "ReleaseDate",
  RUNTIME: "Runtime",
  ADULT: "Adult",
  COUNTRY_IDS: "CountryIDS",
  LANGUAGE_IDS: "LanguageIDS",
  SELECT: "Select",
  GAUTAM_SOLANKI: "@Gautam Solanki",
  DESIGN_CREATED_BY: "Design ©2023 Created by",
};
