import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ApolloProvider from "@/provider/ApolloProvider";
import { authOptions, getServerAuthSession } from "@/lib/auth";
import SessionProviderWrapper from "@/lib/SessionProviderWrapper";
import { redirect } from "next/navigation";
import { ToastProvider } from "./(userroute)/_components/TostProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AntdRegistry>
          <ToastProvider />
          <SessionProviderWrapper>
            <ApolloProvider>{children}</ApolloProvider>
          </SessionProviderWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
